# Generated by Django 5.0.7 on 2024-07-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_user_address_user_birth_date_user_gender_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Regular', 'Regular')], default='Regular', max_length=20),
        ),
    ]
